[options]
admin_passwd = $pbkdf2-sha512$600000$f88551wrxZgTwphT6h0DIA$eVIOFjX9jhNlYonin2aX8ULkFPlWwdVMTEOFw6BXEIAnorD5Y5MXLykyFoP6zXv5BxOd5uDKGgIGYY4RgzQSGg
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = C:\Odoo19\server\odoo\addons,C:\Odoo19\server\addons,C:\Odoo19\custom_addons

